### ISSUE TITLE
teensy 3 version of this code

### ISSUE THREAD

**Issue by abzman** [seanauff/classic-car-sensor-interface#1]
I know it's been months, but I finally got some adorable little hp bubble displays with SPI backpacks and was going to take a crack at building/modifying one of these for my own classic car.  Do you have any board designs or code that you'd be willing to publish that isn't already up here?

**Comment by seanauff** [comment]
Just uploaded latest code and schematics/board designs!

**Comment by abzman** [comment]
Thanks, I was thinking about trying to shoehorn this into it for OBD-II simulation: http://www.instructables.com/id/Arduino-OBD2-Simulator and maybe change up the displays from the RGB led backlit hd44780 to some of these: http://www.ebay.com/itm/281718967006 and a noritake 24x6 vfd

**Comment by seanauff** [comment]
Neat. OBD simulation is something that I have wanted to implement for a while now. Also [this guy](http://www.reddit.com/r/ArduinoProjects/comments/39ueza/the_development_stages_of_my_car_monitoring_system/) is using a VFD and some of my code for his project.
