### ISSUE TITLE
Ignition Coil Interface 

### ISSUE THREAD

**Issue by JayMonkey** [seanauff/classic-car-sensor-interface#2]
Hi,

I came across your project on Reddit ... unfortunately  that thread is archived so not possible to post there so hopeing you see this to answer my question.

Your circuit to interface the Arduino/Tinsey to the ignition coil looks simple and efficient so I built the circuit and it works with a signal generator very well

++ output of generator wired to TACH_SIGNAL
--   output of generator wired to GND

However, i'm confused as to how its actually wired to a ignition coil since most classic cars pulse the negative side of the coil from the dizzy ...

But looking at the direction of the diodes it looks like the TACHO_SIGNAL on your circuit is designed to to be wired to a positive pulsed input ?

Surely the + side of the ignition coil is just a static +12 supply ? so i don't understand how you physically wired the circuit to the cars ignition system.

Would really appreciate if you could expand on this a bit more on this and clarify exactly how to wire it to a car so that a Arduino/Tinsey can be used as a Tacho ..

One other observation .... in you circuit diagram you have the GND signals of the input and the output
 of the opto-isolator connected together .. surely this  negates the whole point of using a opto isolator (or at least part of it) if any large voltage or spike hit the GND side of the car it could damage the Arduino/Tinsey even worse if you had a PC connected then it could also fry its USB port or worse ?

Would this slight modification to your circuit offer better opto isolation ?

![ign-pulse modified](https://user-images.githubusercontent.com/5662056/40549692-12c0f332-6030-11e8-89f3-240314662020.png)

Many Thanks in advance
Cheers
Jay

**Comment by seanauff** [comment]
Hey,

You are correct the coil is negative side switched, and that is exactly where the signal input to the circuit is attached. As the distributor makes and breaks contact, that negative side is either connected to ground or left floating. When grounded, it is nominally at 0 V, and when left floating, it is at the level of the supply, +12 V. Of course there is all the noise and coil ringing, but that is what the circuit is designed to eliminate!

The main purpose of the opto-isolater is to get a nice clean voltage for the input to the microcontroller. Ground isolating would be nicer, but a lot of the other sensor inputs I'm using need to be chassis ground referenced anyway.

**Comment by JayMonkey** [comment]
Hi,

Many thanks for your reply, so if i follow you correctly you have wired it as follows : -

![coil interface-wired](https://user-images.githubusercontent.com/5662056/40576065-5ce83dea-60e8-11e8-963f-023e91532991.png)

If this is correct then what i find odd is that there is no positive on the input side (anode) of the opto-isolator ? ..... If thats the case and it works then great but i'm confused as i always thought an input to a opto-isolator should have both + and -   as essentially its a LED ?

Sorry if this seems a dumb question ... i'm just being hesitant before wiring up to the car as i don't want to blow the MPU and/or the isolator.

Thanks again in advance.
Cheers
Jay

**Comment by seanauff** [comment]
The input to the opto-isolator is positive whenever the points are not connected. Because there is no path from the coil to GND, the negative terminal is at +12 V. This is because (almost) no current is flowing, so there is no voltage drop over the coil.

**Comment by JayMonkey** [comment]
Hi Seanaff,

Thank you so much for the explanation ... I did not realise that the coil 'bleeds' high like that when the points are not connected so it makes much mores sense now ... 

Will try connecting the circuit as detailed in diagram above  tomorrow ... hopefully it will work well.

Many thanks for your help on explaining how your circuit works ....

Cheers
Jay

**Comment by seanauff** [comment]
Good luck! let me know if it works!

**Comment by tmargot** [comment]
Hi, What diode is D3?

**Comment by seanauff** [comment]
> Hi, What diode is D3?

Zener diode, 5.1 V
