### ISSUE TITLE
A thank you and a question

### ISSUE THREAD

**Issue by fall-apart-dave** [seanauff/classic-car-sensor-interface#3]
Hello

I am currently building a dashboard for my hotrod. I have a good deal of my code already written, and it seems you and I were thinking very alike when we started out. I hope you don't mind, but I am going to pinch one or two lines of your code as there are parts that are much more elegent than mine, especially your rev counter! 

I'm wondering, what car did you write this for? 

If you are interested, mine is called Bad Juju the Volksrod, the briefest of google searches brings up a host of pictures though none are very recent (I stopped updating my build threads some time ago). 

Anyway, thank you for sharing your code, it has been really helpful!

**Comment by seanauff** [comment]
Hey that why the code is on here, so you can use as much as you like! The car I made this for is my father's 1964 Thunderbird. This video from from a cruise in they went to recently: https://www.youtube.com/watch?v=nZqCmaQdl58
car is seen at 12:30 and 18:03. Glad you have found this useful!

**Comment by fall-apart-dave** [comment]
Cheers for the reply!! I'll keep you posted how I get on.

Cool car!!!

**Comment by gearmesh** [comment]
I'm having a hard time finding an H11LMS optocoupler? Will a H11L be the same?
