### ISSUE TITLE
Looking at the "Tachometer filter circuit"...

### ISSUE THREAD

**Issue by gearmesh** [seanauff/classic-car-sensor-interface#4]
Looking at the "Tachometer filter circuit"...
Not knowing anything about H11LMS optocouplers and I can't find that exact model in the diagram, which on the ones at Jameco site will work? 

https://www.jameco.com/shop/StoreCatalogDrillDownView?langId=-1&storeId=10001&catalogId=10001&search_type=mfgr&freeText=**H11L*

H11L1M ?
H11L2M ?
H11L3M ?
Thanks for the help. 
Greg

**Comment by seanauff** [comment]
@gearmesh I used a H11L1MS, accoridng to the [datasheet](https://www.jameco.com/Jameco/Products/ProdDS/871341.pdf) the last S just means surface mount so get whatever version is easier for you. As for the 1,2, or 3, I used the 1 version.
